### ISSUE TITLE
Not an issue. 

### ISSUE THREAD

**Issue by raghudotcc** [jhvanderschee/brackettest#1]
Hi Joost,

I changed the code a little to suit my needs and wrote a small blogpost inspired by your solution. Thanks a lot. 
Here: https://www.raghuveer.net/wiki-style-links-in-jekyll/

Thanks,
Raghuveer S

**Comment by jhvanderschee** [comment]
Great! I think markdown handles internal links pretty good. No need to implement a second solution IMO. Thank you for the reference! Much appreciated.

**Comment by raghudotcc** [comment]
Markdown does handle links pretty well, but I thought the syntax was pretty cumbersome when having to insert a link, I.e., unlike in popular wiki markups where just double square brackets are sufficient to specify a link, having to add a bracket and then a parentheses is pretty tedious imo. Anyway thanks for the response. :)
